<script setup lang="ts">
import { computed, ref } from 'vue'
import { Activity, Flag, PauseCircle, Search, Users } from 'lucide-vue-next'
import { activities, teams } from '@/mock/data'
import { useAppStore } from '@/stores/app'

const app = useAppStore()
const tab = ref<'活动管理'|'小队管理'>('活动管理')
const query = ref('')
const offline = ref<Record<string,string>>({})
const selected = ref<{ id:string; title:string; kind:'活动'|'小队' }|null>(null)
const reason = ref('')
const error = ref('')
const activityRows = computed(() => activities.filter(item => `${item.title}${item.organizer.nickname}`.toLowerCase().includes(query.value.toLowerCase())))
const teamRows = computed(() => teams.filter(item => item.name.toLowerCase().includes(query.value.toLowerCase())))
function openOffline(id:string,title:string,kind:'活动'|'小队'){selected.value={id,title,kind};reason.value='';error.value=''}
function confirmOffline(){if(!reason.value.trim()){error.value='下架或停用时必须填写原因。';return};if(selected.value){offline.value[selected.value.id]=reason.value;app.showToast(`${selected.value.kind}已${selected.value.kind==='活动'?'下架':'停用'}，原因已记录`)};selected.value=null}
function restore(id:string,kind:'活动'|'小队'){delete offline.value[id];app.showToast(`${kind}已恢复正常功能`)}
</script>
<template><div><div class="admin-page-title"><div><h1>内容治理</h1><p>管理已发布活动与兴趣小队，处理违规下架和恢复。</p></div></div><div class="content-stats"><div><Activity /><b>1,284</b><span>在线活动</span></div><div><Users /><b>386</b><span>活跃小队</span></div><div><PauseCircle /><b>18</b><span>已下架内容</span></div><div><Flag /><b>26</b><span>待处理举报</span></div></div><section class="admin-card"><div class="content-head"><div><button v-for="item in ['活动管理','小队管理'] as const" :key="item" :class="{active:tab===item}" @click="tab=item">{{ item }}</button></div><label><Search :size="15" /><input v-model="query" placeholder="搜索名称或发起人" /></label></div><div class="content-row content-table-head"><span>内容信息</span><span>发起人 / 加入方式</span><span>状态</span><span>参与规模</span><span>最近更新</span><span>操作</span></div><template v-if="tab==='活动管理'"><div v-for="item in activityRows" :key="item.id" class="content-row"><div><img :src="item.cover" /><span><b>{{ item.title }}</b><small>{{ item.category }} · {{ item.district }}</small></span></div><span>{{ item.organizer.nickname }}</span><span><i :class="{stopped:offline[item.id]}">{{ offline[item.id]?'已下架':'在线' }}</i><small v-if="offline[item.id]" :title="offline[item.id]">{{ offline[item.id] }}</small></span><span>{{ item.joined }} / {{ item.capacity }}</span><span class="muted">今天 10:24</span><div><button class="tiny-btn">查看</button><button v-if="!offline[item.id]" class="tiny-btn offline" @click="openOffline(item.id,item.title,'活动')">下架</button><button v-else class="tiny-btn restore" @click="restore(item.id,'活动')">恢复</button></div></div></template><template v-else><div v-for="item in teamRows" :key="item.id" class="content-row"><div><img :src="item.cover" /><span><b>{{ item.name }}</b><small>{{ item.tags.join(' · ') }}</small></span></div><span>{{ item.joinMode }}</span><span><i :class="{stopped:offline[item.id]}">{{ offline[item.id]?'已停用':'正常' }}</i><small v-if="offline[item.id]">{{ offline[item.id] }}</small></span><span>{{ item.members }} / {{ item.capacity }}</span><span class="muted">昨天 18:06</span><div><button class="tiny-btn">查看</button><button v-if="!offline[item.id]" class="tiny-btn offline" @click="openOffline(item.id,item.name,'小队')">停用</button><button v-else class="tiny-btn restore" @click="restore(item.id,'小队')">恢复</button></div></div></template></section><div v-if="selected" class="govern-modal" @click.self="selected=null"><div><h2>{{ selected.kind==='活动'?'下架活动':'停用小队' }}</h2><p>操作对象：{{ selected.title }}。原有信息会保留，处理完成后可以恢复。</p><textarea v-model="reason" :placeholder="`请输入${selected.kind==='活动'?'下架':'停用'}原因（必填）`"></textarea><small v-if="error">{{ error }}</small><footer><button class="btn btn-outline" @click="selected=null">取消</button><button class="btn btn-dark" @click="confirmOffline">确认操作</button></footer></div></div></div></template>
<style scoped>.content-stats{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin-bottom:18px}.content-stats>div{padding:17px;background:#fff;border:1px solid var(--color-line);border-radius:12px;display:grid;grid-template-columns:38px 1fr;align-items:center}.content-stats svg{grid-row:1/3;width:34px;height:34px;padding:8px;border-radius:9px;background:var(--color-primary-soft);color:var(--color-primary)}.content-stats b{font-size:19px}.content-stats span{color:var(--color-ink-soft);font-size:9px}.content-head{display:flex;justify-content:space-between;margin-bottom:17px}.content-head>div button{padding:9px 13px;border:0;border-radius:7px;background:none;font-weight:700}.content-head>div button.active{background:var(--color-ink);color:#fff}.content-head label{padding:8px 10px;border:1px solid var(--color-line);border-radius:8px;display:flex;gap:6px}.content-head input{border:0;outline:0}.content-row{display:grid;grid-template-columns:1.5fr .7fr .6fr .6fr .6fr .7fr;gap:12px;align-items:center;padding:12px 0;border-top:1px solid var(--color-line);font-size:10px}.content-table-head{color:var(--color-ink-soft);font-size:8px;font-weight:800}.content-row>div:first-child{display:flex;align-items:center;gap:9px}.content-row img{width:50px;height:38px;border-radius:7px;object-fit:cover}.content-row>div:first-child span,.content-row>span:nth-child(3){display:flex;flex-direction:column}.content-row small{max-width:120px;margin-top:4px;color:var(--color-ink-soft);font-size:8px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.content-row>span>i{width:max-content;padding:5px 7px;border-radius:5px;background:var(--color-mint-soft);color:var(--color-mint);font-style:normal}.content-row>span>i.stopped{background:#ffeaed;color:var(--color-danger)}.content-row>div:last-child{display:flex;gap:4px}.offline{color:var(--color-danger)}.restore{color:var(--color-mint)}.govern-modal{position:fixed;z-index:100;inset:0;padding:18px;background:rgba(13,21,34,.55);display:grid;place-items:center}.govern-modal>div{width:min(100%,450px);padding:28px;background:#fff;border-radius:16px}.govern-modal p{color:var(--color-ink-soft);font-size:11px}.govern-modal textarea{width:100%;min-height:95px;padding:11px;border:1px solid var(--color-line);border-radius:9px}.govern-modal small{color:var(--color-danger)}.govern-modal footer{display:flex;justify-content:flex-end;gap:8px;margin-top:18px}.govern-modal .btn{padding:10px 14px;font-size:11px}@media(max-width:750px){.content-stats{grid-template-columns:1fr 1fr}.content-table-head{display:none}.content-row{grid-template-columns:1fr auto}.content-row>span{display:none}.content-head{gap:12px;flex-direction:column}}</style>
