<script setup lang="ts">
import { Check, Filter, Search, ShieldAlert, X } from 'lucide-vue-next'
import { computed, ref } from 'vue'
import { reviewTasks } from '@/mock/data'
import { useAppStore } from '@/stores/app'
const app=useAppStore(); const tasks=ref(reviewTasks.map(x=>({...x}))); const tab=ref('全部待办'); const selected=ref(reviewTasks[0]); const query=ref(''); const rejecting=ref<string|null>(null); const reason=ref(''); const reasonError=ref('')
const visibleTasks=computed(()=>tasks.value.filter(task=>(tab.value==='全部待办'?task.status==='待审核':task.type===tab.value&&task.status==='待审核')&&`${task.title}${task.submitter}`.toLowerCase().includes(query.value.toLowerCase())))
function approve(id:string){const task=tasks.value.find(x=>x.id===id);if(task){task.status='已通过';app.showToast('审核已通过，结果已记录')}}
function openReject(id:string){rejecting.value=id;reason.value='';reasonError.value=''}
function confirmReject(){if(!reason.value.trim()){reasonError.value='驳回时必须填写原因。';return};const task=tasks.value.find(x=>x.id===rejecting.value);if(task){task.status='已驳回';task.reason=`驳回原因：${reason.value}`};rejecting.value=null;app.showToast('已驳回并记录原因')}
</script>
<template><div><div class="admin-page-title"><div><h1>审核中心</h1><p>处理活动、商家认证与用户举报任务。</p></div><button class="btn btn-dark btn-sm"><ShieldAlert :size="16" />审核规则配置</button></div><div class="review-toolbar"><div class="review-tabs"><button v-for="item in ['全部待办','活动审核','商家认证','举报处理']" :key="item" :class="{active:tab===item}" @click="tab=item">{{ item }}<span v-if="item==='全部待办'">{{ visibleTasks.length }}</span></button></div><div><label><Search :size="15" /><input v-model="query" placeholder="搜索任务" /></label><button class="tiny-btn"><Filter :size="14" />筛选</button></div></div><section class="review-table admin-card"><div class="table-head"><span>审核对象</span><span>触发原因</span><span>风险等级</span><span>提交时间</span><span>状态 / 操作</span></div><div v-for="task in visibleTasks" :key="task.id" class="table-row" @click="selected=task"><div><b>{{ task.title }}</b><small>{{ task.type }} · {{ task.submitter }}</small></div><span>{{ task.reason }}</span><span><i :class="`risk risk-${task.risk}`">{{ task.risk }}风险</i></span><span class="muted">{{ task.submittedAt }}</span><div><button class="action-pass" title="通过" @click.stop="approve(task.id)"><Check :size="14" /></button><button class="action-reject" title="驳回" @click.stop="openReject(task.id)"><X :size="14" /></button></div></div><div v-if="!visibleTasks.length" class="empty-review">当前筛选下没有待办任务</div></section><section class="review-detail admin-card"><div class="admin-card-head"><div><h2>AI 风险分析 · {{ selected.title }}</h2><small class="muted">模型仅提供辅助判断，最终结果由审核员确认</small></div><span class="risk risk-高">置信度 87%</span></div><div class="analysis-grid"><div><b>风险摘要</b><p>该活动涉及夜间水上项目，且预计参与人数超过 50 人，已按平台规则转入人工审核。</p></div><div><b>建议核查</b><ul><li>发起方水上运动经营资质</li><li>参与者保险与救生装备方案</li><li>恶劣天气取消和退款机制</li></ul></div><div><b>材料完整度</b><p><strong>4 / 5</strong> 缺少应急救援联系人证明</p></div></div></section><div v-if="rejecting" class="reject-modal" @click.self="rejecting=null"><div><h2>填写驳回原因</h2><p>原因会反馈给提交方，用于修改后重新提交。</p><textarea v-model="reason" placeholder="请明确说明不通过的规则依据或缺失材料"></textarea><small v-if="reasonError">{{ reasonError }}</small><footer><button class="btn btn-outline" @click="rejecting=null">取消</button><button class="btn btn-dark" @click="confirmReject">确认驳回</button></footer></div></div></div></template>
<style scoped>.review-toolbar{margin-bottom:16px;display:flex;justify-content:space-between;align-items:center}.review-tabs{display:flex;gap:4px}.review-tabs button{padding:9px 12px;border:0;border-radius:8px;background:transparent;color:var(--color-ink-soft);font-size:11px;font-weight:700}.review-tabs button.active{background:#fff;color:var(--color-ink);box-shadow:var(--shadow-soft)}.review-tabs span{margin-left:5px;padding:2px 5px;border-radius:7px;background:var(--color-primary);color:#fff;font-size:8px}.review-toolbar>div:last-child{display:flex;gap:7px}.review-toolbar label{padding:8px 10px;border:1px solid var(--color-line);border-radius:8px;background:#fff;display:flex;gap:6px}.review-toolbar input{border:0;outline:0;background:none}.tiny-btn{display:flex;align-items:center;gap:5px}.review-table{padding:0;overflow:hidden}.table-head,.table-row{display:grid;grid-template-columns:1.3fr 1.4fr .6fr .5fr .7fr;gap:15px;align-items:center;padding:13px 18px}.table-head{background:#fafafa;color:var(--color-ink-soft);font-size:9px;font-weight:800}.table-row{border-top:1px solid var(--color-line);font-size:10px;cursor:pointer}.table-row:hover{background:#fffcfa}.table-row>div:first-child{display:flex;flex-direction:column}.table-row small{margin-top:4px;color:var(--color-ink-soft)}.table-row>div:last-child{display:flex;gap:5px}.action-pass,.action-reject{width:27px;height:27px;border:0;border-radius:6px;display:grid;place-items:center}.action-pass{background:var(--color-mint-soft);color:var(--color-mint)}.action-reject{background:#ffeaed;color:var(--color-danger)}.passed{color:var(--color-mint)}.rejected{color:var(--color-danger)}.review-detail{margin-top:17px}.analysis-grid{display:grid;grid-template-columns:1fr 1fr .6fr;gap:20px}.analysis-grid>div{padding:15px;border-radius:9px;background:#f7f7f7}.analysis-grid b{font-size:11px}.analysis-grid p,.analysis-grid li{color:var(--color-ink-soft);font-size:9px;line-height:1.8}.analysis-grid ul{padding-left:15px}.analysis-grid strong{display:block;color:var(--color-ink);font-size:24px}@media(max-width:800px){.review-toolbar{align-items:flex-start;flex-direction:column;gap:12px}.review-tabs{flex-wrap:wrap}.table-head{display:none}.table-row{grid-template-columns:1fr auto}.table-row>span{display:none}.analysis-grid{grid-template-columns:1fr}}</style>
