<script setup lang="ts">
import { Check, ExternalLink, Filter, Search, ShieldAlert, X } from 'lucide-vue-next'
import { computed, onMounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import { useAppStore } from '@/stores/app'
import { apiGet, apiPost } from '@/lib/api'
import type { ReviewTask } from '@/types'
const app=useAppStore(); const router=useRouter(); const tasks=ref<ReviewTask[]>([]); const tab=ref('全部待办'); const selected=ref<ReviewTask|null>(null); const query=ref(''); const rejecting=ref<string|null>(null); const reason=ref(''); const reasonError=ref(''); const ruleOpen=ref(false); const riskFilter=ref<'全部风险'|'低'|'中'|'高'>('全部风险')
const fallbackTask: ReviewTask = { id: '', type: '活动审核', title: '暂无待办', submitter: '', risk: '低', reason: '', submittedAt: '', status: '待审核', targetId: '' }
function goDetail(task: ReviewTask) {
  if (!task.targetId) return
  if (task.type === '活动审核') router.push({ path: `/admin/activities/${task.targetId}`, query: { reviewId: task.id } })
}
const visibleTasks=computed(()=>tasks.value.filter(task=>(tab.value==='全部待办'?task.status==='待审核':task.type===tab.value&&task.status==='待审核')&&(riskFilter.value==='全部风险'||task.risk===riskFilter.value)&&`${task.title}${task.submitter}`.toLowerCase().includes(query.value.toLowerCase())))
const selectedTask=computed(()=>selected.value ?? visibleTasks.value[0] ?? fallbackTask)
async function loadReviews(){tasks.value=await apiGet<ReviewTask[]>('/admin/reviews'); if(!selected.value && tasks.value.length) selected.value=tasks.value[0]}
async function approve(id:string){await apiPost<void>(`/admin/reviews/${id}/approve`, { handlerId:'admin' }); app.showToast('审核已通过，结果已记录'); await loadReviews()}
function openReject(id:string){rejecting.value=id;reason.value='';reasonError.value=''}
async function confirmReject(){if(!reason.value.trim()){reasonError.value='驳回时必须填写原因。';return};await apiPost<void>(`/admin/reviews/${rejecting.value}/reject`, { reason:reason.value, handlerId:'admin' });rejecting.value=null;selected.value=null;app.showToast('已驳回并记录原因');await loadReviews()}
onMounted(loadReviews)
</script>
<template><div><div class="admin-page-title"><div><h1>审核中心</h1><p>处理活动、商家认证与用户举报任务。</p></div><button class="btn btn-dark btn-sm" @click="ruleOpen=true"><ShieldAlert :size="16" />审核规则配置</button></div><div class="review-toolbar"><div class="review-tabs"><button v-for="item in ['全部待办','活动审核','商家认证','举报处理']" :key="item" :class="{active:tab===item}" @click="tab=item">{{ item }}<span v-if="item==='全部待办'">{{ visibleTasks.length }}</span></button></div><div><label><Search :size="15" /><input v-model="query" placeholder="搜索任务" /></label><select v-model="riskFilter" class="risk-select"><option>全部风险</option><option>低</option><option>中</option><option>高</option></select><button class="tiny-btn" @click="riskFilter='全部风险';query=''"><Filter :size="14" />重置</button></div></div><section class="review-table admin-card"><div class="table-head"><span>审核对象</span><span>触发原因</span><span>风险等级</span><span>提交时间</span><span>状态 / 操作</span><span></span></div><div v-for="task in visibleTasks" :key="task.id" class="table-row" @click="selected=task"><div><b>{{ task.title }}</b><small>{{ task.type }} · {{ task.submitter }}</small></div><span>{{ task.reason }}</span><span><i :class="`risk risk-${task.risk}`">{{ task.risk }}风险</i></span><span class="muted">{{ task.submittedAt }}</span><div><button class="action-pass" title="通过" @click.stop="approve(task.id)"><Check :size="14" /></button><button class="action-reject" title="驳回" @click.stop="openReject(task.id)"><X :size="14" /></button></div><div><button v-if="task.targetId" class="action-detail" title="查看详情" @click.stop="goDetail(task)"><ExternalLink :size="14" /></button></div></div><div v-if="!visibleTasks.length" class="empty-review">当前筛选下没有待办任务</div></section><section class="review-detail admin-card"><div class="admin-card-head"><div><h2>AI 风险分析 · {{ selectedTask.title }}</h2><small class="muted">模型仅提供辅助判断，最终结果由审核员确认</small></div><span class="risk risk-高">置信度 87%</span></div><div class="analysis-grid"><div><b>风险摘要</b><p>{{ selectedTask.reason || '暂无风险摘要' }}</p></div><div><b>建议核查</b><ul><li>活动时间、地点和安全须知是否完整</li><li>商家资质与提交材料是否一致</li><li>大规模或高风险活动是否具备应急预案</li></ul></div><div><b>材料完整度</b><p><strong>{{ selectedTask.id ? 4 : 0 }} / 5</strong> 根据提交内容动态核查</p></div></div></section><div v-if="ruleOpen" class="reject-modal" @click.self="ruleOpen=false"><div><h2>审核规则配置</h2><p>超过 50 人、高风险标签、第三方审核异常会进入人工队列；后台处理会写入审核记录和审计日志。</p><footer><button class="btn btn-dark" @click="ruleOpen=false">知道了</button></footer></div></div><div v-if="rejecting" class="reject-modal" @click.self="rejecting=null"><div><h2>填写驳回原因</h2><p>原因会反馈给提交方，用于修改后重新提交。</p><textarea v-model="reason" placeholder="请明确说明不通过的规则依据或缺失材料"></textarea><small v-if="reasonError">{{ reasonError }}</small><footer><button class="btn btn-outline" @click="rejecting=null">取消</button><button class="btn btn-dark" @click="confirmReject">确认驳回</button></footer></div></div></div></template>
<style scoped>.review-toolbar{margin-bottom:16px;display:flex;justify-content:space-between;align-items:center}.review-tabs{display:flex;gap:4px}.review-tabs button{padding:9px 12px;border:0;border-radius:8px;background:transparent;color:var(--color-ink-soft);font-size:11px;font-weight:700}.review-tabs button.active{background:#fff;color:var(--color-ink);box-shadow:var(--shadow-soft)}.review-tabs span{margin-left:5px;padding:2px 5px;border-radius:7px;background:var(--color-primary);color:#fff;font-size:8px}.review-toolbar>div:last-child{display:flex;gap:7px}.review-toolbar label{padding:8px 10px;border:1px solid var(--color-line);border-radius:8px;background:#fff;display:flex;gap:6px}.review-toolbar input{border:0;outline:0;background:none}.tiny-btn{display:flex;align-items:center;gap:5px}.review-table{padding:0;overflow:hidden}.table-head,.table-row{display:grid;grid-template-columns:1.3fr 1.4fr .6fr .5fr .5fr .2fr;gap:15px;align-items:center;padding:13px 18px}.table-head{background:#fafafa;color:var(--color-ink-soft);font-size:9px;font-weight:800}.table-row{border-top:1px solid var(--color-line);font-size:10px;cursor:pointer}.table-row:hover{background:#fffcfa}.table-row>div:first-child{display:flex;flex-direction:column}.table-row small{margin-top:4px;color:var(--color-ink-soft)}.table-row>div:nth-last-child(2){display:flex;gap:5px}.action-pass,.action-reject{width:27px;height:27px;border:0;border-radius:6px;display:grid;place-items:center}.action-pass{background:var(--color-mint-soft);color:var(--color-mint)}.action-reject{background:#ffeaed;color:var(--color-danger)}.action-detail{width:27px;height:27px;border:0;border-radius:6px;display:grid;place-items:center;background:var(--color-bg);color:var(--color-primary)}.action-detail:hover{background:#e8e4fb}.passed{color:var(--color-mint)}.rejected{color:var(--color-danger)}.review-detail{margin-top:17px}.analysis-grid{display:grid;grid-template-columns:1fr 1fr .6fr;gap:20px}.analysis-grid>div{padding:15px;border-radius:9px;background:#f7f7f7}.analysis-grid b{font-size:11px}.analysis-grid p,.analysis-grid li{color:var(--color-ink-soft);font-size:9px;line-height:1.8}.analysis-grid ul{padding-left:15px}.analysis-grid strong{display:block;color:var(--color-ink);font-size:24px}@media(max-width:800px){.review-toolbar{align-items:flex-start;flex-direction:column;gap:12px}.review-tabs{flex-wrap:wrap}.table-head{display:none}.table-row{grid-template-columns:1fr auto}.table-row>span{display:none}.analysis-grid{grid-template-columns:1fr}}</style>
<style scoped>
.risk-select{padding:8px;border:1px solid var(--color-line);border-radius:8px;background:#fff;font-size:11px}
</style>
