CREATE DATABASE IF NOT EXISTS quju_dev
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'quju_app'@'localhost';
CREATE USER IF NOT EXISTS 'quju_app'@'127.0.0.1';

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX, DROP, REFERENCES
  ON quju_dev.* TO 'quju_app'@'localhost';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX, DROP, REFERENCES
  ON quju_dev.* TO 'quju_app'@'127.0.0.1';

FLUSH PRIVILEGES;

