<script setup lang="ts">
import { CalendarDays, Camera, CheckCircle2, ChevronRight, Heart, MapPin, QrCode, Settings, Star, Users } from 'lucide-vue-next'
import ActivityCard from '@/components/activity/ActivityCard.vue'
import { activities, currentUser } from '@/mock/data'
</script>
<template><div class="container profile-page"><section class="profile-cover"><div class="profile-pattern"></div><button><Camera :size="16" />更换封面</button></section><section class="profile-main"><img :src="currentUser.avatar" /><div class="profile-copy"><div><h1>{{ currentUser.nickname }} <CheckCircle2 :size="18" /></h1><span class="location"><MapPin :size="14" />{{ currentUser.city }}</span></div><p>{{ currentUser.bio }}</p><div class="tag-row"><span v-for="tag in currentUser.interests" :key="tag"># {{ tag }}</span></div></div><div class="profile-stats"><div><b>{{ currentUser.following }}</b><span>关注</span></div><div><b>{{ currentUser.followers }}</b><span>粉丝</span></div><div><b>{{ currentUser.credit }}</b><span>信用分</span></div></div><button class="btn btn-outline"><Settings :size="17" />编辑资料</button></section><div class="profile-grid"><main><div class="profile-tabs"><button class="active">我的活动</button><button>动态</button><button>收藏</button><button>活动总结</button></div><div class="activity-grid"><ActivityCard v-for="activity in activities.slice(0,2)" :key="activity.id" :activity="activity" /></div></main><aside><div class="side-card"><h3>我的快捷入口</h3><RouterLink to="/check-in"><QrCode />扫码签到<ChevronRight /></RouterLink><RouterLink to="/teams"><Users />我的小队<ChevronRight /></RouterLink><RouterLink to="/create"><CalendarDays />活动管理<ChevronRight /></RouterLink><RouterLink to="/discover"><Heart />我的收藏<ChevronRight /></RouterLink></div><div class="side-card credit"><div><Star :size="20" /><b>信用表现优秀</b></div><strong>{{ currentUser.credit }}<small>/100</small></strong><p>按时参与、友善交流，让每次相遇都更安心。</p></div></aside></div></div></template>
<style scoped>
.profile-page{padding:30px 0 70px}.profile-cover{position:relative;height:220px;overflow:hidden;border-radius:var(--radius-xl);background:linear-gradient(120deg,#ffad87,#ff6b45 40%,#7256c7)}.profile-pattern{position:absolute;inset:0;background:radial-gradient(circle at 18% 120%,transparent 0 110px,rgba(255,255,255,.1) 111px 150px,transparent 151px),radial-gradient(circle at 85% -20%,transparent 0 100px,rgba(255,255,255,.1) 101px 155px,transparent 156px)}.profile-cover button{position:absolute;right:18px;top:18px;padding:8px 11px;border:0;border-radius:var(--radius-pill);background:rgba(255,255,255,.85);display:flex;gap:5px;font-size:10px}.profile-main{position:relative;margin:-55px 26px 0;min-height:150px;padding:22px 25px 22px 155px;border-radius:var(--radius-lg);background:#fff;box-shadow:var(--shadow-card);display:flex;align-items:center;gap:20px}.profile-main>img{position:absolute;left:25px;top:-35px;width:112px;height:112px;border:5px solid #fff;border-radius:30px;object-fit:cover}.profile-copy{flex:1}.profile-copy>div:first-child{display:flex;align-items:center;gap:12px}.profile-copy h1{display:flex;align-items:center;gap:6px;margin:0;font-size:25px}.profile-copy h1 svg{color:var(--mint)}.location{display:flex;align-items:center;color:var(--color-ink-soft);font-size:10px}.profile-copy p{margin:9px 0;color:var(--color-ink-soft);font-size:12px}.profile-stats{display:flex;gap:24px}.profile-stats div{display:flex;align-items:center;flex-direction:column}.profile-stats b{font-size:18px}.profile-stats span{color:var(--color-ink-soft);font-size:9px}.profile-main>.btn{font-size:11px}.profile-grid{display:grid;grid-template-columns:1fr 280px;gap:20px;margin-top:30px}.profile-tabs{display:flex;gap:22px;margin-bottom:18px;border-bottom:1px solid var(--color-line)}.profile-tabs button{padding:12px 2px;border:0;border-bottom:2px solid transparent;background:none;color:var(--color-ink-soft);font-weight:700}.profile-tabs button.active{border-color:var(--color-primary);color:var(--color-ink)}.profile-grid .activity-grid{grid-template-columns:1fr 1fr}.side-card{margin-bottom:15px;padding:20px;background:#fff;border:1px solid var(--color-line);border-radius:var(--radius-md)}.side-card h3{font-size:14px}.side-card>a{padding:11px 0;border-bottom:1px solid var(--color-line);display:flex;align-items:center;gap:9px;font-size:11px}.side-card>a svg:first-child{width:16px;color:var(--color-primary)}.side-card>a svg:last-child{width:14px;margin-left:auto;color:var(--color-ink-soft)}.credit{background:var(--color-ink);color:#fff}.credit>div{display:flex;align-items:center;gap:7px;color:var(--color-sun);font-size:12px}.credit strong{display:block;margin:15px 0 7px;font-size:35px}.credit strong small{font-size:12px;color:#8f98a8}.credit p{margin:0;color:#aab1bf;font-size:9px;line-height:1.7}
@media(max-width:900px){.profile-main{padding-top:85px;padding-left:25px;align-items:flex-start;flex-wrap:wrap}.profile-main>img{left:25px}.profile-stats{margin-left:auto}.profile-grid{grid-template-columns:1fr}.profile-grid aside{display:grid;grid-template-columns:1fr 1fr;gap:14px}}@media(max-width:600px){.profile-cover{height:160px}.profile-main{margin:-35px 10px 0}.profile-main>img{width:90px;height:90px}.profile-copy{min-width:100%}.profile-copy>div:first-child{align-items:flex-start;flex-direction:column}.profile-stats{margin-left:0}.profile-main>.btn{margin-left:auto}.profile-grid .activity-grid{grid-template-columns:1fr}.profile-grid aside{grid-template-columns:1fr}}
</style>
